# backend/universe.py

STOCKS = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS", "LT.NS", "SBIN.NS", "AXISBANK.NS", "KOTAKBANK.NS", "HDFCAMC.NS","HCLTECH.NS",
"INDUSINDBK.NS", "TATACONSUM.NS", "NESTLEIND.NS", "CONCOR.NS", "LUPIN.NS", "MARUTI.NS", "POLYCAB.NS", "SUNPHARMA.NS", "PETRONET.NS", "CHOLAFIN.NS", 
"IPCALAB.NS", "INDIGO.NS", "CIPLA.NS", "DIXON.NS", "SHREECEM.NS", "IRCTC.NS", "ASHOKLEY.NS", "BAJAJFINSV.NS", "GLENMARK.NS", "TORNTPHARM.NS",
"ASTRAL.NS", "HEROMOTOCO.NS", "MRF.NS", "APOLLOHOSP.NS", "AUROPHARMA.NS", "POWERGRI.NS", "MCX.NS", "BOSCHLTD.NS", "ALKEM.NS", "TRENT.NS", "HAL.NS",
"IDFC.NS", "HINDUNILVR.NS", "LAURUSLABS.NS", "BAJFINANCE.NS", "SBILIFE.NS", "DLF.NS", "TVSMOTOR.NS", "BHARTIARTL.NS", "ABB.NS", "GODREJCP.NS", "BERGEPAINT.NS", 
"APOLLOTYRE.NS", "COALINDIA.NS", "FEDERALBNK.NS", "HAVELLS.NS", "NTPC.NS", "GMRINFRA.NS", "SHRIRAMFIN.NS", "BRITANNIA.NS", "ABBOTINDIA.NS", 
"CHAMBLFERT.NS", "ULTRACEMCO.NS", "TITAN.NS", "AARTIIND.NS", "VEDL.NS", "LALPATHLAB.NS", "PERSISTENT.NS", "M&M.NS", "HDFCLIFE.NS", "PIIND.NS", "BALRAMCHIN.NS", 
"DEEPAKNTR.NS", "OFSS.NS", "M&MFIN.NS", "HINDCOPPER.NS", "AUBANK.NS", "BSOFT.NS", "COROMANDEL.NS", "GUJGASLTD.NS", "BHARATFORG.NS", "ASIANPAINT.NS", "SIEMENS.NS", 
"TATACHEM.NS",  "ADANIPORTS.NS", "LTTS.NS", "CROMPTON.NS", "BALKRISIND.NS", "RBLBANK.NS", "TECHM.NS", "MUTHOOTFIN.NS", "ZYDUSLIFE.NS", "DABUR.NS", "LTF.NS", 
"TATAPOWER.NS", "PNB.NS", "DIVISLAB.NS", "MANAPPURAM.NS", "LICHSGFIN.NS", "KOTAKBANK.NS", "TATASTEEL.NS", "INDIAMART.NS", "EICHERMOT.NS", "BATAINDIA.NS", 
"TATACOMM.NS", "ITC.NS", "IDFCFIRSTB.NS", "SRF.NS", "ICICIPRULI.NS", "BEL.NS", "CUMMINSIND.NS", "ABCAPITAL.NS", "HINDPETRO.NS", "SAIL.NS", "RAMCOCEM.NS", "EXIDEIND.NS", 
"NATIONALUM.NS", "GAIL.NS", "ICICIGI.NS", "DALBHARAT.NS", "MFSL.NS", "GODREJPROP.NS", "COLPAL.NS", "JKCEMENT.NS", "ACC.NS", "NAVINFLUOR.NS", "JUBLFOOD.NS", 
"GRANULES.NS", "CANFINHOME.NS", "PIDILITIND.NS", "HINDALCO.NS", "CANBK.NS", "JSWSTEEL.NS", "GRASIM.NS", "MOTHERSON.NS", "BAJAJ-AUTO.NS", "LTIM.NS", "DELTACORP.NS", 
"VOLTAS.NS", "AMBUJACEM.NS", "DRREDDY.NS", "SBICARD.NS", "WIPRO.NS", "JINDALSTEL.NS", "COFORGE.NS", "BHEL.NS", "BANKBARODA.NS", "INDUSTOWER.NS", "BIOCON.NS", "INDIACEM.NS", 
"SYNGENE.NS", "NAUKRI.NS", "JIOFIN.NS", "MPHASIS.NS", "BANDHANBNK.NS"
]
