// This file simulates the result of a daily, comprehensive VCP scan.
// In a real application, this data might be generated by a backend process
// and fetched by the client. For this frontend-only app, we hardcode the results.

const VCP_CANDIDATES: string[] = [
    'POLYCAB.NS',
    'KEI.NS',
    'ASTRAL.NS',
    'PAGEIND.NS',
    'TRENT.NS',
    'DIXON.NS',
    'DEEPAKNTR.NS',
    'CAMS.NS',
    'APLAPOLLO.NS',
    'BALKRISIND.NS',
    'VINATIORGA.BO',
    'IEX.NS',
    'IRCON.NS',
    'TRITURBINE.NS',
    'ZENSARTECH.NS',
    'AFFLE.NS',
    'ROUTE.BO',
    'LAURUSLABS.BO',
    'HAPPSTMNDS.BO',
    'CDSL.BO',
    'TEJASNET.NS',
    'ENDURANCE.BO',
    'ANGELONE.NS',
    'PERSISTENT.NS',
    'TATAPOWER.BO',
    'JINDALSTEL.BO',
    'TATAELXSI.NS',
    'HAL.NS',
    'JSWENERGY.NS',
    'BEL.NS',
    'HINDZINC.BO',
    'RVNL.BO'
];

/**
 * Returns a list of stock symbols that have been pre-identified as
 * showing signs of a Volatility Contraction Pattern (VCP).
 */
export const getVcpCandidates = (): string[] => {
    return VCP_CANDIDATES;
};
