
import type { Stock } from '../types.ts';

// A representative list of NSE/BSE stocks for the scanner to analyze.
// In a real-world application, this would come from an API.
const STOCKS: Stock[] = [
  // NSE Large Cap
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'INFY.NS', name: 'Infosys', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ITC.NS', name: 'ITC Limited', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'LICI.NS', name: 'Life Insurance Corporation of India', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'WIPRO.NS', name: 'Wipro', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'TITAN.NS', name: 'Titan Company', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports & SEZ', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'NTPC.NS', name: 'NTPC', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'ONGC.NS', name: 'ONGC', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'COALINDIA.NS', name: 'Coal India', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'CIPLA.NS', name: 'Cipla', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'DIVISLAB.NS', name: 'Divi\'s Laboratories', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'M&M.NS', name: 'Mahindra & Mahindra', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'DRREDDY.NS', name: 'Dr. Reddy\'s Laboratories', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'UPL.NS', name: 'UPL Limited', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'SBILIFE.NS', name: 'SBI Life Insurance', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'HDFCLIFE.NS', name: 'HDFC Life Insurance', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'IOC.NS', name: 'Indian Oil Corporation', exchange: 'NSE', marketCap: 'Large' },
  { symbol: 'GAIL.NS', name: 'GAIL (India)', exchange: 'NSE', marketCap: 'Large' },
  
  // NSE Mid Cap
  { symbol: 'PAGEIND.NS', name: 'Page Industries', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'VOLTAS.NS', name: 'Voltas', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ASTRAL.NS', name: 'Astral', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'TATACHEM.NS', name: 'Tata Chemicals', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'CUMMINSIND.NS', name: 'Cummins India', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'TRENT.NS', name: 'Trent', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'MRF.NS', name: 'MRF', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'SIEMENS.NS', name: 'Siemens', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ZOMATO.NS', name: 'Zomato', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'HAVELLS.NS', name: 'Havells India', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'SRF.NS', name: 'SRF Limited', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'INDUSTOWER.NS', name: 'Indus Towers', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'LTIM.NS', name: 'LTIMindtree', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'IRCTC.NS', name: 'IRCTC', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'COLPAL.NS', name: 'Colgate-Palmolive', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'DABUR.NS', name: 'Dabur India', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'MARICO.NS', name: 'Marico', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'PIIND.NS', name: 'PI Industries', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'HAL.NS', name: 'Hindustan Aeronautics', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'SAIL.NS', name: 'Steel Authority of India', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'NMDC.NS', name: 'NMDC', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'VEDL.NS', name: 'Vedanta', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'DLF.NS', name: 'DLF', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'GLAND.NS', name: 'Gland Pharma', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'TORNTPOWER.NS', name: 'Torrent Power', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'CONCOR.NS', name: 'Container Corporation', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Kubota', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'HINDZINC.NS', name: 'Hindustan Zinc', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'IBULHSGFIN.NS', name: 'Indiabulls Housing Finance', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'LUPIN.NS', name: 'Lupin', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'RAMCOCEM.NS', name: 'Ramco Cements', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'SHRIRAMFIN.NS', name: 'Shriram Finance', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'UBL.NS', name: 'United Breweries', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'IDEA.NS', name: 'Vodafone Idea', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'ZEEL.NS', name: 'Zee Entertainment', exchange: 'NSE', marketCap: 'Mid' },
  { symbol: 'MCDOWELL-N.NS', name: 'United Spirits', exchange: 'NSE', marketCap: 'Mid' },

  // NSE Small Cap
  { symbol: 'KEI.NS', name: 'KEI Industries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CAMS.NS', name: 'Computer Age Management Services', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ANGELONE.NS', name: 'Angel One', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TEJASNET.NS', name: 'Tejas Networks', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'AFFLE.NS', name: 'Affle (India)', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'WELSPUNIND.NS', name: 'Welspun India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IRCON.NS', name: 'Ircon International', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TRITURBINE.NS', name: 'Triveni Turbine', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'APLAPOLLO.NS', name: 'APL Apollo Tubes', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IDFCFIRSTB.NS', name: 'IDFC First Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'LUXIND.NS', name: 'Lux Industries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'FINOLEXIND.NS', name: 'Finolex Industries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JKLAKSHMI.NS', name: 'JK Lakshmi Cement', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'VGUARD.NS', name: 'V-Guard Industries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JUSTDIAL.NS', name: 'Just Dial', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'PVR.NS', name: 'PVR', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RADICO.NS', name: 'Radico Khaitan', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'PHOENIXLTD.NS', name: 'Phoenix Mills', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JUBILANT.NS', name: 'Jubilant Foodworks', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ZENSARTECH.NS', name: 'Zensar Technologies', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'BSE.NS', name: 'BSE Limited', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CDSL.NS', name: 'Central Depository Services', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ROUTE.NS', name: 'Route Mobile', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GREENCITY.NS', name: 'Godrej Properties', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'HFCL.NS', name: 'HFCL', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'MASTEK.NS', name: 'Mastek', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'NBCC.NS', name: 'NBCC (India)', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'NCC.NS', name: 'NCC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'NHPC.NS', name: 'NHPC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'PFC.NS', name: 'Power Finance Corporation', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RBLBANK.NS', name: 'RBL Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RVNL.NS', name: 'Rail Vikas Nigam', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SUNTV.NS', name: 'Sun TV Network', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SYNGENE.NS', name: 'Syngene International', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TEAMLEASE.NS', name: 'TeamLease Services', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TRIDENT.NS', name: 'Trident', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TTML.NS', name: 'Tata Teleservices', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'UJJIVANSFB.NS', name: 'Ujjivan Small Finance Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'WELCORP.NS', name: 'Welspun Corp', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'AIAENG.NS', name: 'AIA Engineering', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'AKZOINDIA.NS', name: 'Akzo Nobel India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ALLCARGO.NS', name: 'Allcargo Logistics', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Batteries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'BBTC.NS', name: 'Bombay Burmah Trading', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'BLUEDART.NS', name: 'Blue Dart Express', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CEATLTD.NS', name: 'CEAT', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CESC.NS', name: 'CESC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CHAMBLFERT.NS', name: 'Chambal Fertilisers', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CREDITACC.NS', name: 'CreditAccess Grameen', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'CYIENT.NS', name: 'Cyient', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'EIDPARRY.NS', name: 'EID Parry', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ENGINERSIN.NS', name: 'Engineers India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'FDC.NS', name: 'FDC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'FORTIS.NS', name: 'Fortis Healthcare', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GMRINFRA.NS', name: 'GMR Infrastructure', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GNFC.NS', name: 'Gujarat Narmada Valley', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GRANULES.NS', name: 'Granules India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GRAPHITE.NS', name: 'Graphite India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'GSFC.NS', name: 'Gujarat State Fertilizers', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'HEG.NS', name: 'HEG', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'HUDCO.NS', name: 'HUDCO', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IBREALEST.NS', name: 'Indiabulls Real Estate', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IDFC.NS', name: 'IDFC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'INDIACEM.NS', name: 'India Cements', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'INDHOTEL.NS', name: 'Indian Hotels Company', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'IPCALAB.NS', name: 'IPCA Laboratories', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'ITI.NS', name: 'ITI Limited', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JBCHEPHARM.NS', name: 'J.B. Chemicals', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JINDALSAW.NS', name: 'Jindal Saw', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JKCEMENT.NS', name: 'JK Cement', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'JKPAPER.NS', name: 'JK Paper', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'KANSAINER.NS', name: 'Kansai Nerolac Paints', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'KEC.NS', name: 'KEC International', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'LEMONTREE.NS', name: 'Lemon Tree Hotels', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'METROPOLIS.NS', name: 'Metropolis Healthcare', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'MMTC.NS', name: 'MMTC', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates Projects', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'QUESS.NS', name: 'Quess Corp', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RAYMOND.NS', name: 'Raymond', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RCF.NS', name: 'Rashtriya Chemicals', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'REDINGTON.NS', name: 'Redington India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'RELAXO.NS', name: 'Relaxo Footwears', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SONATSOFTW.NS', name: 'Sonata Software', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SOUTHBANK.NS', name: 'South Indian Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SPICEJET.NS', name: 'SpiceJet', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'STAR.NS', name: 'Strides Pharma Science', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SUMICHEM.NS', name: 'Sumitomo Chemical', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TASTYBITE.NS', name: 'Tasty Bite Eatables', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TATAMETALI.NS', name: 'Tata Metaliks', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'THERMAX.NS', name: 'Thermax', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TIMKEN.NS', name: 'Timken India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TTKPRESTIG.NS', name: 'TTK Prestige', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'VAIBHAVGBL.NS', name: 'Vaibhav Global', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'VTL.NS', name: 'Vardhman Textiles', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool of India', exchange: 'NSE', marketCap: 'Small' },
  { symbol: 'WOCKPHARMA.NS', name: 'Wockhardt', exchange: 'NSE', marketCap: 'Small' },

  // BSE Large Cap
  { symbol: 'ASIANPAINT.BO', name: 'Asian Paints', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'BAJFINANCE.BO', name: 'Bajaj Finance', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'AXISBANK.BO', name: 'Axis Bank', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'LT.BO', name: 'Larsen & Toubro', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'ULTRACEMCO.BO', name: 'UltraTech Cement', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'SUNPHARMA.BO', name: 'Sun Pharmaceutical Industries', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'M&M.BO', name: 'Mahindra & Mahindra', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'DRREDDY.BO', name: 'Dr. Reddy\'s Laboratories', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'WIPRO.BO', name: 'Wipro', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'HCLTECH.BO', name: 'HCL Technologies', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'TITAN.BO', name: 'Titan Company', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'ITC.BO', name: 'ITC Limited', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'RELIANCE.BO', name: 'Reliance Industries', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'TCS.BO', name: 'Tata Consultancy Services', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'HDFCBANK.BO', name: 'HDFC Bank', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'INFY.BO', name: 'Infosys', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'ICICIBANK.BO', name: 'ICICI Bank', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'HINDUNILVR.BO', name: 'Hindustan Unilever', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'KOTAKBANK.BO', name: 'Kotak Mahindra Bank', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'SBIN.BO', name: 'State Bank of India', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'BHARTIARTL.BO', name: 'Bharti Airtel', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'BAJAJFINSV.BO', name: 'Bajaj Finserv', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'MARUTI.BO', name: 'Maruti Suzuki', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'HDFCLIFE.BO', name: 'HDFC Life Insurance', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'TATASTEEL.BO', name: 'Tata Steel', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'POWERGRID.BO', name: 'Power Grid Corporation', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'NTPC.BO', name: 'NTPC', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'ONGC.BO', name: 'ONGC', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'INDUSINDBK.BO', name: 'IndusInd Bank', exchange: 'BSE', marketCap: 'Large' },
  { symbol: 'TECHM.BO', name: 'Tech Mahindra', exchange: 'BSE', marketCap: 'Large' },

  // BSE Mid Cap
  { symbol: 'BATAINDIA.BO', name: 'Bata India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'VINATIORGA.BO', name: 'Vinati Organics', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ABFRL.BO', name: 'Aditya Birla Fashion and Retail', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'MFSL.BO', name: 'Max Financial Services', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'GLAND.BO', name: 'Gland Pharma', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'CASTROLIND.BO', name: 'Castrol India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ENDURANCE.BO', name: 'Endurance Technologies', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: '3MINDIA.BO', name: '3M India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'GODREJIND.BO', name: 'Godrej Industries', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'APOLLOTYRE.BO', name: 'Apollo Tyres', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'TATAPOWER.BO', name: 'Tata Power', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'NMDC.BO', name: 'NMDC', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ACC.BO', name: 'ACC', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'BANKINDIA.BO', name: 'Bank of India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'FEDERALBNK.BO', name: 'Federal Bank', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'UNIONBANK.BO', name: 'Union Bank of India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'JINDALSTEL.BO', name: 'Jindal Steel & Power', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'SAIL.BO', name: 'Steel Authority of India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ADANIPOWER.BO', name: 'Adani Power', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'PETRONET.BO', name: 'Petronet LNG', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'GODREJPROP.BO', name: 'Godrej Properties', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'TRENT.BO', name: 'Trent', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'SIEMENS.BO', name: 'Siemens', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'SRF.BO', name: 'SRF Limited', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'HAVELLS.BO', name: 'Havells India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'LTIM.BO', name: 'LTIMindtree', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'PNB.BO', name: 'Punjab National Bank', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ICICIPRULI.BO', name: 'ICICI Prudential Life', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'BANKBARODA.BO', name: 'Bank of Baroda', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'AMBUJACEM.BO', name: 'Ambuja Cements', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'BERGEPAINT.BO', name: 'Berger Paints', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'BEL.BO', name: 'Bharat Electronics', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'CHOLAFIN.BO', name: 'Cholamandalam Investment', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'COLPAL.BO', name: 'Colgate-Palmolive', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'DABUR.BO', name: 'Dabur India', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'DLF.BO', name: 'DLF', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'HAL.BO', name: 'Hindustan Aeronautics', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'HINDZINC.BO', name: 'Hindustan Zinc', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'ICICIGI.BO', name: 'ICICI Lombard', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'INDIGO.BO', name: 'InterGlobe Aviation', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'LUPIN.BO', name: 'Lupin', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'MARICO.BO', name: 'Marico', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'MPHASIS.BO', name: 'Mphasis', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'MUTHOOTFIN.BO', name: 'Muthoot Finance', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'OFSS.BO', name: 'Oracle Financial Services', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'PIDILITIND.BO', name: 'Pidilite Industries', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'SHRIRAMFIN.BO', name: 'Shriram Finance', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'TATACONSUM.BO', name: 'Tata Consumer Products', exchange: 'BSE', marketCap: 'Mid' },
  { symbol: 'TORNTPOWER.BO', 'name': 'Torrent Power', 'exchange': 'BSE', 'marketCap': 'Mid' },

  // BSE Small Cap
  { symbol: 'LAURUSLABS.BO', name: 'Laurus Labs', exchange: 'BSE', marketCap: 'Small' },
  { symbol: 'CDSL.BO', name: 'Central Depository Services', exchange: 'BSE', marketCap: 'Small' },
  { symbol: 'RAJESHEXPO.BO', name: 'Rajesh Exports', exchange: 'BSE', marketCap: 'Small' },
  { symbol: 'ITI.BO', name: 'ITI Limited', exchange: 'BSE', marketCap: 'Small' },
  { 'symbol': 'BLS.BO', 'name': 'BLS International Services', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'ROUTE.BO', 'name': 'Route Mobile', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'EQUITASBNK.BO', 'name': 'Equitas Small Finance Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'VAIBHAVGBL.BO', 'name': 'Vaibhav Global', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'SPICEJET.BO', 'name': 'SpiceJet', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'IDFC.BO', 'name': 'IDFC Limited', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'RBLBANK.BO', 'name': 'RBL Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'UCOBANK.BO', 'name': 'UCO Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'IOB.BO', 'name': 'Indian Overseas Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'CENTRALBK.BO', 'name': 'Central Bank of India', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'HFCL.BO', 'name': 'HFCL', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'NCC.BO', 'name': 'NCC', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'RVNL.BO', 'name': 'Rail Vikas Nigam', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'PNBHOUSING.BO', 'name': 'PNB Housing Finance', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'SOUTHBANK.BO', 'name': 'South Indian Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'DISHTV.BO', 'name': 'Dish TV India', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'AARTIDRUGS.BO', 'name': 'Aarti Drugs', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'AAVAS.BO', 'name': 'Aavas Financiers', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'AFFLE.BO', 'name': 'Affle (India)', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'AIAENG.BO', 'name': 'AIA Engineering', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'APLAPOLLO.BO', 'name': 'APL Apollo Tubes', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'ASTERDM.BO', 'name': 'Aster DM Healthcare', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'BALAMINES.BO', 'name': 'Balaji Amines', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'BSE.BO', 'name': 'BSE Limited', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'CAMS.BO', 'name': 'Computer Age Management', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'CENTURYPLY.BO', 'name': 'Century Plyboards', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'CHEMCON.BO', 'name': 'Chemcon Speciality', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'CIGNITITEC.BO', 'name': 'Cigniti Technologies', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'COCHINSHIP.BO', 'name': 'Cochin Shipyard', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'DIXON.BO', 'name': 'Dixon Technologies', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'ECLERX.BO', 'name': 'eClerx Services', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'FINCABLES.BO', 'name': 'Finolex Cables', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'GATEWAY.BO', 'name': 'Gateway Distriparks', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'GRINFRA.BO', 'name': 'G R Infraprojects', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'HAPPSTMNDS.BO', 'name': 'Happiest Minds', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'IEX.BO', 'name': 'Indian Energy Exchange', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'IIFL.BO', 'name': 'IIFL Finance', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'IRCON.BO', 'name': 'Ircon International', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'J&KBANK.BO', 'name': 'Jammu & Kashmir Bank', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'JUBILANT.BO', 'name': 'Jubilant Foodworks', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'JUSTDIAL.BO', 'name': 'Just Dial', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'KEI.BO', 'name': 'KEI Industries', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'LUXIND.BO', 'name': 'Lux Industries', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'MASTEK.BO', 'name': 'Mastek', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'NATCOPHARM.BO', 'name': 'Natco Pharma', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'NBCC.BO', 'name': 'NBCC (India)', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'PVRINOX.BO', 'name': 'PVR Inox', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'RADICO.BO', 'name': 'Radico Khaitan', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'RENUKA.BO', 'name': 'Shree Renuka Sugars', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'SOBHA.BO', 'name': 'Sobha', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'TANLA.BO', 'name': 'Tanla Platforms', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'TEJASNET.BO', 'name': 'Tejas Networks', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'TRITURBINE.BO', 'name': 'Triveni Turbine', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'VGUARD.BO', 'name': 'V-Guard Industries', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'WELSPUNIND.BO', 'name': 'Welspun India', 'exchange': 'BSE', 'marketCap': 'Small' },
  { 'symbol': 'ZENSARTECH.BO', 'name': 'Zensar Technologies', 'exchange': 'BSE', 'marketCap': 'Small' },
];


export const getStocks = (): Stock[] => {
  return STOCKS;
};